### PR TITLE
Modal react component

### PR DESCRIPTION
**Pull request by noloman**

### CODE REVIEW

**Comment by noloman** [comment]
Can somebody please check it out now? I made some improvements yesterday!
Thanks!

Op di 23 okt. 2018 19:32 schreef Álvaro Casado Coscollá <
notifications@github.com>:

**Comment by alvarocasadoc** [comment]
Looking awesome! Everything is being displayed as expected :100: Great job on this one :clap: :tada:

**Comment by alvarocasadoc** [comment]
So quick! :laughing:

**Comment by noloman** [comment]
I was looking forward to it haha! Thanks for the help :)

**Pull request merged**
