### PR TITLE
Issue 138 pagination

### PR DESCRIPTION
**Pull request by X140hu4**
PR regarding issue #138 Component: Pagination

At the moment the component accepts two parameters: 
- `nrPages` The number of pages (default: 2)
- `curPage` The current page (default: 1)

A few questions arose while working on this:
- Would there be a limit on the number of pages? 
- How is state managed?

I think the following tasks are remaining:
- [ ] Implementing button component from issue #148 
- [ ] Simplify class using `classnames`
- [ ] add handleclick to change page when clicking on Back/Next buttons
- [ ] add handleclick for pages to change page

I welcome any suggestion or comment :)

### CODE REVIEW

**Comment by Diphendara** [comment]
Hi @X140hu4 i will answer your questions
- No
- We don't apply redux yet, for now we are just making a "library" of components to future use.

**Comment by alvarocasadoc** [comment]
Hi, Fabien! :wave: Thank you so much for working on this. I've seen your storybook stories and the component is looking awesome :100: If you have any questions don't hesitate to ask us :wink:

**Comment by alvarocasadoc** [comment]
Hey, @X140hu4, how are you doing with this component? Have you made any progress? 😄

**Comment by alvarocasadoc** [comment]
Closed due to inactivity :disappointed:

**Pull request closed without merging**
